---
title: "Step 1: Machine Learning"
output: html_notebook
---

SET WORKING DIRECTORY AND LOAD PACKAGES

```{r}
setwd("N:/GISdata/_GIS_Projects/BIKES TOO 2016/GIS/Models_scripts/biketoo")

library (party)
library(lattice)
```

LOAD MODEL DATA

```{r}
model_data <- read.csv(file="N:/GISdata/_GIS_Projects/BIKES TOO 2016/GIS/Project_data/Final/biketoo_master_analysis_table.csv", header=TRUE, sep=",")
names(model_data)
all_inj_set <- subset(model_data, select = c(3, 9:102))
```

SET SEED AND CREATE CONDITIONAL RANDOM FOREST SET

```{r}
set.seed(12345)

crf<- cforest(all_inj_set$all_bike ~ ., data = all_inj_set,
control = cforest_unbiased(mtry = 8, ntree = 5))
```

CALCULATE STANDARD IMPORTANCE

```{r}
crf.varimp <-varimp(crf,mincriterion=0.95)

crf.varimp1<-sort(crf.varimp,decreasing = F)
crf.varimp1

write.table(sort(crf.varimp,decreasing = T), file="VarImp_PVST_Int001.txt")

png(file="VarImp_PVST_Int001.png",height = 10, width = 8,units = "in",  res = 500 );

dotplot(crf.varimp1,  main="Variable Importance-SEA   PVST_Int",xlab="Variable Importance by cforest (predictors to right of dashed vertical line are
significant)", cex.main=0.1, cex.xlab=0.5,panel = function(x,y){
panel.dotplot(x, y, col="darkblue", pch=16, cex=1.0)
panel.abline(v=abs(min(crf.varimp1)), col="red",lty="longdash", lwd=2)
panel.abline(v=0, col="blue")
})
dev.off()
```

